extern const GeoLayout MY_HUB_area_1_geo[];
extern const GeoLayout MY_HUB_area_1[];
extern const Collision MY_HUB_area_1_collision[];
extern const MacroObject MY_HUB_area_1_macro_objs[];
extern u8 MY_HUB_dl_castle_grounds_textures_03800_rgba16_ci8[];
extern u8 MY_HUB_dl_castle_grounds_textures_03800_rgba16_pal_rgba16[];
extern u8 MY_HUB_dl_castle_grounds_textures_04000_rgba16_ci8[];
extern u8 MY_HUB_dl_castle_grounds_textures_04000_rgba16_pal_rgba16[];
extern Vtx MY_HUB_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx MY_HUB_dl_Level_Mesh_mesh_layer_1_vtx_0[16];
extern Gfx MY_HUB_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx MY_HUB_dl_Level_Mesh_mesh_layer_1_vtx_1[12];
extern Gfx MY_HUB_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Gfx mat_MY_HUB_dl_Grass_Example[];
extern Gfx mat_revert_MY_HUB_dl_Grass_Example[];
extern Gfx mat_MY_HUB_dl_Grass[];
extern Gfx mat_revert_MY_HUB_dl_Grass[];
extern Gfx MY_HUB_dl_Level_Mesh_mesh_layer_1[];
